# Generated by Django 3.1.7 on 2021-04-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=200)),
                ('steps', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('recipes', models.ManyToManyField(to='pages.Recipes')),
            ],
        ),
    ]
