# Generated by Django 3.1.7 on 2021-04-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('minutes', models.IntegerField()),
                ('steps', models.JSONField()),
                ('nutrition', models.JSONField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('n_ratings', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='pages.Ingredient')),
            ],
        ),
    ]
