# Generated by Django 3.1.7 on 2021-04-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ingredients',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
